//
// Created by bclaus on 5/14/17.
//

#ifndef X86ID_LEAF2DESC_H
#define X86ID_LEAF2DESC_H

enum LEAF2 {
    NULL_DESC = 0x0,
    INST_TLB_4KB_4WAY_32ENTRIES = 0x1,
    INST_TLB_4MB_FULL_2ENTRIES = 0x2,
    DATA_TLB_4KB_4WAY_64ENTRIES = 0x3,
    DATA_TLB_4MB_4WAY_8ENTRIES = 0x4,
    DATA_TLB1_4MB_4WAY_32ENTRIES = 0x5,
    INST_CACHE_LEVEL1_8KB_4WAY_32BYTELINE = 0x6,
    // 1
    INST_CACHE_LEVEL1_16KB_4WAY_32BYTELINE = 0x8,
    INST_CACHE_LEVEL1_32KB_4WAY_64BYTELINE = 0x9,
    DATA_CACHE_LEVEL1_8KB_2WAY_32BYTELINE = 0xA,
    INST_TLB_4MB_4WAY_4ENTRIES = 0xB,
    DATA_CACHE_LEVEL1_16KB_4WAY_32BYTELINE = 0xC,
    DATA_CACHE_LEVEL1_16KB_4WAY_64BYTELINE = 0xD,
    DATA_CACHE_LEVEL1_24KB_6WAY_64BYTELINE = 0xE,
    // 14
    CACHE_LEVEL2_128KB_2WAY_64BYTELINE = 0x1D,
    // 3
    CACHE_LEVEL2_256KB_8WAY_64BYTELINE = 0x21,
    CACHE_LEVEL3_512KB_4WAY_64BYTELINE_2LINESECTOR,
    CACHE_LEVEL3_1MB_8WAY_64BYTELINE_2LINESECTOR,
    CACHE_LEVEL2_1MB_16WAY_64BYTELINE,
    CACHE_LEVEL3_2MB_8WAY_64BYTELINE_2LINESECTOR = 0x25,
    // 3
    CACHE_LEVEL3_4MB_8WAY_64BYTELINE_2LINESECTOR = 0x29,
    // 2
    DATA_CACHE_LEVEL1_32KB_8WAY_64BYTELINE = 0x2C,
    // 3
    INST_CACHE_LEVEL1_32KB_8WAY_64BYTELINE = 0x30,
    // 15
    NO_LEVEL2_OR_LEVEL3_CACHE = 0x40,      // if the processor has a valid L2, no L3 cache
    CACHE_LEVEL2_128KB_4WAY_32BYTELINE,
    CACHE_LEVEL2_256KB_4WAY_32BYTELINE,
    CACHE_LEVEL2_512KB_4WAY_32BYTELINE,
    CACHE_LEVEL2_1MB_4WAY_32BYTELINE,
    CACHE_LEVEL2_2MB_4WAY_32BYTELINE,
    CACHE_LEVEL3_4MB_4WAY_64BYTELINE,
    CACHE_LEVEL3_8MB_8WAY_64BYTELINE,
    CACHE_LEVEL2_3MB_12WAY_64BYTELINE,
    CACHE_LEVEL2_4MB_16WAY_64BYTELINE, // Looks to have multiple definitions in the intel manual
    CACHE_LEVEL3_6MB_12WAY_64BYTELINE,
    CACHE_LEVEL3_8MB_16WAY_64BYTELINE,
    CACHE_LEVEL3_12MB_12WAY_64BYTELINE,
    CACHE_LEVEL3_16MB_16WAY_64BYTELINE,
    CACHE_LEVEL2_6MB_24WAY_64BYTELINE,
    INST_TLB_4KB_32ENTRIES,
    INST_TLB_4KB_2MB_4MB_64ENTRIES,
    INST_TLB_4KB_2MB_4MB_128ENTRIES,
    INST_TLB_4KB_2MB_4MB_256ENTRIES = 0x52,
    // 2
    INST_TLB_2MB_4MB_FULL_7ENTRIES = 0x55,
    DATA_TLB0_4MB_4WAY_16ENTRIES,
    DATA_TLB0_4KB_4WAY_16ENTRIES,
    // 1
    DATA_TLB0_4KB_FULL_16ENTRIES = 0x59,
    DATA_TLB0_2MB_4MB_4WAY_32ENTRIES,
    DATA_TLB_4KB_4MB_64ENTRIES,
    DATA_TLB_4KB_4MB_128ENTRIES,
    DATA_TLB_4KB_4MB_256ENTRIES = 0x5D,
    // 2
    DATA_CACHE_LEVEL1_16KB_8WAY_64BYTELINE = 0x60,
    INST_TLB_4KB_FULL_48ENTRIES = 0x61,
    // 1
    DATA_TLB_2MB_4MB_4WAY_32ENTRIES_ARRAY = 0x63, // Separate array with 1GB pages, 4way set associative, 4 entries
    DATA_TLB_4KB_4WAY_512ENTRIES,
    DATA_CACHE_LEVEL1_8KB_4WAY_64BYTELINE = 0x66,
    DATA_CACHE_LEVEL1_16KB_4WAY_64BYTELINE__duplicate, // intel duplicated some descriptors...
    DATA_CACHE_LEVEL1_32KB_4WAY_64BYTELINE,
    UTLB_4KB_8WAY_64ENTRIES = 0x6A,
    DTLB_4KB_8WAY_256ENTRIES,
    DTLB_2MB_4MB_8WAY_128ENTRIES,
    DTLB_1GB_FULL_16ENTRIES,
    TRACE_CACHE_12KOP_8WAY = 0x70,
    TRACE_CACHE_16KOP_8WAY,
    TRACE_CACHE_32KOP_8WAY,
    INST_TLB_2MB_4MB_FULL_8ENTRIES = 0x76,
    CACHE_LEVEL2_1MB_4WAY_64BYTELINE,
    CACHE_LEVEL2_128KB_8WAY_64BYTELINE_2LINESECTOR,
    CACHE_LEVEL2_256KB_8WAY_64BYTELINE_2LINESECTOR,
    CACHE_LEVEL2_512KB_8WAY_64BYTELINE_2LINESECTOR,
    CACHE_LEVEL2_1MB_8WAY_64BYTELINE_2LINESECTOR,
    CACHE_LEVEL2_2MB_8WAY_64BYTELINE,
    CACHE_LEVEL2_512KB_2WAY_64BYTELINE = 0x7F,
    CACHE_LEVEL2_512KB_8WAY_64BYTELINE,
    CACHE_LEVEL2_256KB_8WAY_32BYTELINE = 0x82,
    CACHE_LEVEL2_512KB_8WAY_32BYTELINE,
    CACHE_LEVEL2_1MB_8WAY_32BYTELINE,
    CACHE_LEVEL2_2MB_8WAY_32BYTELINE,
    CACHE_LEVEL2_512KB_4WAY_64BYTELINE,
    CACHE_LEVEL2_1MB_8WAY_64BYTELINE,
    DTLB_4KB_FULL_32ENTRIES = 0xA0,
    INST_TLB_4KB_4WAY_128ENTRIES = 0xB0,
    INST_TLB_2MB_4WAY_8ENTRIES_or_4MB_4WAY_4ENTRIES,
    INST_TLB_4KB_4WAY_64ENTRIES,
    DATA_TLB_4KB_4WAY_128ENTRIES,
    DATA_TLB1_4KB_4WAY_256ENTRIES,
    INST_TLB_4KB_8WAY_64ENTRIES,
    INST_TLB_4KB_8WAY_128ENTRIES,
    DATA_TLB1_4KB_4WAY_64ENTRIES = 0xBA,
    DATA_TLB_4KB_4MB_4WAY_8ENTRIES = 0xC0,
    STLB_LEVEL2_4KB_2MB_8WAY_1024ENTRIES,
    DTLB_4KB_2MB_4WAY_16ENTRIES,
    STLB_LEVEL2_4KB_2MB_6WAY_1536ENTRIES_ARRAY,
    DTLB_2MB_4MB_4WAY_32ENTRIES,
    STLB_LEVEL2_4KB_4WAY_512ENTRIES = 0xCA,
    CAHCE_LEVEL3_512KB_4WAY_64BYTELINE = 0xD0,
    CACHE_LEVEL3_1MB_4WAY_64BYTELINE,
    CACHE_LEVEL3_2MB_4WAY_64BYTELINE,
    CACHE_LEVEL3_1MB_8WAY_64BYTELINE = 0xD6,
    CACHE_LEVEL3_2MB_8WAY_64BYTELINE,
    CACHE_LEVEL3_4MB_8WAY_64BYTELINE,
    CACHE_LEVEL3_1p5_12WAY_64BYTELINE = 0xDC,
    CACHE_LEVEL3_3MB_12WAY_64BYTELINE,
    CACHE_LEVEL3_6MB_12WAY_64BYTELINE__duplicate, // more duplicates
    CACHE_LEVEL3_2MB_16WAY_64BYTELINE = 0xE2,
    CACHE_LEVEL3_4MB_16WAY_64BYTELINE,
    CACHE_LEVEL3_8MB_16WAY_64BYTELINE__duplicate, // honestly, does intel read their own documentation?
    CACHE_LEVEL3_12MB_24WAY_64BYTELINE = 0xEA,
    CACHE_LEVEL3_18MB_24WAY_64BYTELINE,
    CACHE_LEVEL3_24MB_24WAY_64BYTELINE,
    PREFETCH_64BYTE = 0xF0,
    PREFETCH_128BYTE = 0xF1,


    LEAF_2_NO_REPORT = 0xFF
};

// empty strings are reserved/not defined in intel spec
const char* const leaf2_descriptions[] = {
    "Null descriptor, this byte contains no information",
    "Instruction TLB: 4 KByte pages, 4-way set associative, 32 entries",
    "Instruction TLB: 4 MByte pages, fully associative, 2 entries",
    "Data TLB: 4 KByte pages, 4-way set associative, 64 entries",
    "Data TLB: 4 MByte pages, 4-way set associative, 8 entries",
    "Data TLB1: 4 MByte pages, 4-way set associative, 32 entries",
    "1st-level instruction cache: 8 KBytes, 4-way set associative, 32 byte line size",
    "",
    "1st-level instruction cache: 16 KBytes, 4-way set associative, 32 byte line size",
    "1st-level instruction cache: 32KBytes, 4-way set associative, 64 byte line size",
    "1st-level data cache: 8 KBytes, 2-way set associative, 32 byte line size",
    "Instruction TLB: 4 MByte pages, 4-way set associative, 4 entries",
    "1st-level data cache: 16 KBytes, 4-way set associative, 32 byte line size",
    "1st-level data cache: 16 KBytes, 4-way set associative, 64 byte line size",
    "1st-level data cache: 24 KBytes, 6-way set associative, 64 byte line size",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2nd-level cache: 128 KBytes, 2-way set associative, 64 byte line size",
    "",
    "",
    "",
    "2nd-level cache: 256 KBytes, 8-way set associative, 64 byte line size",
    "3rd-level cache: 512 KBytes, 4-way set associative, 64 byte line size, 2 lines per sector",
    "3rd-level cache: 1 MBytes, 8-way set associative, 64 byte line size, 2 lines per sector",
    "2nd-level cache: 1 MBytes, 16-way set associative, 64 byte line size",
    "3rd-level cache: 2 MBytes, 8-way set associative, 64 byte line size, 2 lines per sector",
    "",
    "",
    "",
    "3rd-level cache: 4 MBytes, 8-way set associative, 64 byte line size, 2 lines per sector",
    "",
    "",
    "1st-level data cache: 32 KBytes, 8-way set associative, 64 byte line size",
    "",
    "",
    "",
    "1st-level instruction cache: 32 KBytes, 8-way set associative, 64 byte line size",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "No 2nd-level cache or, if processor contains a valid 2nd-level cache, no 3rd-level cache",
    "2nd-level cache: 128 KBytes, 4-way set associative, 32 byte line size",
    "2nd-level cache: 256 KBytes, 4-way set associative, 32 byte line size",
    "2nd-level cache: 512 KBytes, 4-way set associative, 32 byte line size",
    "2nd-level cache: 1 MByte, 4-way set associative, 32 byte line size",
    "2nd-level cache: 2 MByte, 4-way set associative, 32 byte line size",
    "3rd-level cache: 4 MByte, 4-way set associative, 64 byte line size",
    "3rd-level cache: 8 MByte, 8-way set associative, 64 byte line size",
    "2nd-level cache: 3MByte, 12-way set associative, 64 byte line size",
    "2nd-level cache: 4 MByte, 16-way set associative, 64 byte line size",
    "3rd-level cache: 6MByte, 12-way set associative, 64 byte line size",
    "3rd-level cache: 8MByte, 16-way set associative, 64 byte line size",
    "3rd-level cache: 12MByte, 12-way set associative, 64 byte line size",
    "3rd-level cache: 16MByte, 16-way set associative, 64 byte line size",
    "2nd-level cache: 6MByte, 24-way set associative, 64 byte line size",
    "Instruction TLB: 4 KByte pages, 32 entries",
    "Instruction TLB: 4 KByte and 2-MByte or 4-MByte pages, 64 entries",
    "Instruction TLB: 4 KByte and 2-MByte or 4-MByte pages, 128 entries",
    "Instruction TLB: 4 KByte and 2-MByte or 4-MByte pages, 256 entries",
    "",
    "",
    "Instruction TLB: 2-MByte or 4-MByte pages, fully associative, 7 entries",
    "Data TLB0: 4 MByte pages, 4-way set associative, 16 entries",
    "Data TLB0: 4 KByte pages, 4-way associative, 16 entries",
    "",
    "Data TLB0: 4 KByte pages, fully associative, 16 entries",
    "Data TLB0: 2 MByte or 4 MByte pages, 4-way set associative, 32 entries",
    "Data TLB: 4 KByte and 4 MByte pages, 64 entries",
    "Data TLB: 4 KByte and 4 MByte pages,128 entries",
    "Data TLB: 4 KByte and 4 MByte pages,256 entries",
    "",
    "",
    "1st-level data cache: 16 KByte, 8-way set associative, 64 byte line size",
    "Instruction TLB: 4 KByte pages, fully associative, 48 entries",
    "",
    "Data TLB: 2 MByte or 4 MByte pages, 4-way set associative, 32 entries and a separate array with 1 GByte pages, 4-way set associative, 4 entries",
    "Data TLB: 4 KByte pages, 4-way set associative, 512 entries",
    "",
    "1st-level data cache: 8 KByte, 4-way set associative, 64 byte line size",
    "1st-level data cache: 16 KByte, 4-way set associative, 64 byte line size",
    "1st-level data cache: 32 KByte, 4-way set associative, 64 byte line size",
    "",
    "uTLB: 4 KByte pages, 8-way set associative, 64 entries",
    "DTLB: 4 KByte pages, 8-way set associative, 256 entries",
    "DTLB: 2M/4M pages, 8-way set associative, 128 entries",
    "DTLB: 1 GByte pages, fully associative, 16 entries",
    "",
    "",
    "Trace cache: 12 K-micro op, 8-way set associative",
    "Trace cache: 16 K-micro op, 8-way set associative",
    "Trace cache: 32 K-μop, 8-way set associative",
    "",
    "",
    "",
    "Instruction TLB: 2M/4M pages, fully associative, 8 entries",
    "",
    "2nd-level cache: 1 MByte, 4-way set associative, 64byte line size",
    "2nd-level cache: 128 KByte, 8-way set associative, 64 byte line size, 2 lines per sector",
    "2nd-level cache: 256 KByte, 8-way set associative, 64 byte line size, 2 lines per sector",
    "2nd-level cache: 512 KByte, 8-way set associative, 64 byte line size, 2 lines per sector",
    "2nd-level cache: 1 MByte, 8-way set associative, 64 byte line size, 2 lines per sector",
    "2nd-level cache: 2 MByte, 8-way set associative, 64byte line size",
    "",
    "2nd-level cache: 512 KByte, 2-way set associative, 64-byte line size",
    "2nd-level cache: 512 KByte, 8-way set associative, 64-byte line size",
    "",
    "2nd-level cache: 256 KByte, 8-way set associative, 32 byte line size",
    "2nd-level cache: 512 KByte, 8-way set associative, 32 byte line size",
    "2nd-level cache: 1 MByte, 8-way set associative, 32 byte line size",
    "2nd-level cache: 2 MByte, 8-way set associative, 32 byte line size",
    "2nd-level cache: 512 KByte, 4-way set associative, 64 byte line size",
    "2nd-level cache: 1 MByte, 8-way set associative, 64 byte line size",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "DTLB: 4k pages, fully associative, 32 entries",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Instruction TLB: 4 KByte pages, 4-way set associative, 128 entries",
    "Instruction TLB: 2M pages, 4-way, 8 entries or 4M pages, 4-way, 4 entries",
    "Instruction TLB: 4KByte pages, 4-way set associative, 64 entries",
    "Data TLB: 4 KByte pages, 4-way set associative, 128 entries",
    "Data TLB1: 4 KByte pages, 4-way associative, 256 entries",
    "Instruction TLB: 4KByte pages, 8-way set associative, 64 entries",
    "Instruction TLB: 4KByte pages, 8-way set associative, 128 entries",
    "",
    "",
    "",
    "Data TLB1: 4 KByte pages, 4-way associative, 64 entries",
    "",
    "",
    "",
    "",
    "",
    "Data TLB: 4 KByte and 4 MByte pages, 4-way associative, 8 entries",
    "Shared 2nd-Level TLB: 4 KByte/2MByte pages, 8-way associative, 1024 entries",
    "DTLB: 4 KByte/2 MByte pages, 4-way associative, 16 entries",
    "Shared 2nd-Level TLB: 4 KByte /2 MByte pages, 6-way associative, 1536 entries. Also 1GBbyte pages, 4-way, 16 entries.",
    "DTLB: 2M/4M Byte pages, 4-way associative, 32 entries",
    "",
    "",
    "",
    "",
    "",
    "Shared 2nd-Level TLB: 4 KByte pages, 4-way associative, 512 entries",
    "",
    "",
    "",
    "",
    "",
    "3rd-level cache: 512 KByte, 4-way set associative, 64 byte line size",
    "3rd-level cache: 1 MByte, 4-way set associative, 64 byte line size",
    "3rd-level cache: 2 MByte, 4-way set associative, 64 byte line size",
    "",
    "",
    "",
    "3rd-level cache: 1 MByte, 8-way set associative, 64 byte line size",
    "3rd-level cache: 2 MByte, 8-way set associative, 64 byte line size",
    "3rd-level cache: 4 MByte, 8-way set associative, 64 byte line size",
    "",
    "",
    "",
    "3rd-level cache: 1.5 MByte, 12-way set associative, 64 byte line size",
    "3rd-level cache: 3 MByte, 12-way set associative, 64 byte line size",
    "3rd-level cache: 6 MByte, 12-way set associative, 64 byte line size",
    "",
    "",
    "",
    "3rd-level cache: 2 MByte, 16-way set associative, 64 byte line size",
    "3rd-level cache: 4 MByte, 16-way set associative, 64 byte line size",
    "3rd-level cache: 8 MByte, 16-way set associative, 64 byte line size",
    "",
    "",
    "",
    "",
    "",
    "3rd-level cache: 12MByte, 24-way set associative, 64 byte line size",
    "3rd-level cache: 18MByte, 24-way set associative, 64 byte line size",
    "3rd-level cache: 24MByte, 24-way set associative, 64 byte line size",
    "",
    "",
    "",
    "64-Byte prefetching",
    "128-Byte prefetching",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "CPUID leaf 2 does not report cache descriptor information, use CPUID leaf 4 to query cache parameters"
};


#endif //X86ID_CACHEDEFS_H
